name: CI Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package*.json'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'package*.json'
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        
    - name: Run linting
      run: |
        npm run lint -- --max-warnings 0
      
    - name: Run tests
      run: npm test
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      env:
        DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/student-crud-api
      run: |
        VERSION=$(node -p "require('./package.json').version")
        docker build -t $DOCKER_IMAGE_NAME:$VERSION .
        docker push $DOCKER_IMAGE_NAME:$VERSION
