name: CI Pipeline

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "package*.json"
      - "Dockerfile"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      NODE_ENV: test
      MONGODB_URI: mongodb://localhost:27017/student_test_db
      PORT: 3000

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint -- --max-warnings 0

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run tests
        run: npm test

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        env:
          DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/student-crud-api
        run: |
          VERSION=$(node -p "require('./package.json').version")
          docker build -t $DOCKER_IMAGE_NAME:$VERSION .
          docker push $DOCKER_IMAGE_NAME:$VERSION
