name: Test Trigger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test
        run: |
          echo "This is a test trigger"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
