name: Test CI Setup

on:
  workflow_dispatch:

jobs:
  test-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check GitHub Actions Runner
        run: |
          echo "Runner OS: $RUNNER_OS"
          echo "Runner Temp: $RUNNER_TEMP"
          echo "GitHub Workspace: $GITHUB_WORKSPACE"
